# Generated by Django 6.0.6 on 2026-06-24 08:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('purchase_order', 'Purchase Order'), ('bank_statement', 'Bank Statement')], default='invoice', max_length=20)),
                ('status', models.CharField(choices=[('extracted', 'Extracted'), ('needs_review', 'Needs Review'), ('confirmed', 'Confirmed'), ('posted', 'Posted to ledger')], default='extracted', max_length=15)),
                ('raw_text', models.TextField(blank=True)),
                ('extracted', models.JSONField(blank=True, default=dict)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('confidence', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_documents', to='ledger.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
