# Generated by Django 6.0.6 on 2026-06-24 08:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=20)),
                ('role', models.CharField(choices=[('generic', 'Generic'), ('cash', 'Cash / Bank'), ('accounts_receivable', 'Accounts Receivable'), ('accounts_payable', 'Accounts Payable'), ('vat_output', 'VAT Output (collected)'), ('vat_input', 'VAT Input (paid)')], default='generic', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='organizations.organization')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=300)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='posted', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'journal entries',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='ledger.account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ledger.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('confidence', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4)),
                ('status', models.CharField(choices=[('uncategorized', 'Uncategorized'), ('categorized', 'AI-categorized'), ('approved', 'Approved'), ('flagged', 'Flagged')], default='uncategorized', max_length=15)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='ledger.transaction')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='organizations.organization')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
